export const metadata = {
    title: "Weather | Search",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return <div className="h-fit">{children}</div>;
}
